name: CI-CD-pipe-to-AWS
env:
  AWS_S3_BUCKET_NAME  : "pet-clinic-task"
  EB_APP_NAME         : "pet-clinic"
  EB_ENVIRONMENT_NAME : "petclinic-env"
  DEPLOYMENT_PACK_NAME: "pet_cl_${{ github.sha }}.zip"
  AWS_REGION          : "eu-west-1"

on: 
  push:
    branches: 
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Clone our repo 
      uses: actions/checkout@v1
    
    - name: Zip package
      run : zip -r ${{ env.DEPLOYMENT_PACK_NAME }} ./ -x *.git*
