name: CI-CD-pipe-to-AWS
env:
  AWS_S3_BUCKET_NAME  : "pet-clinic-task"
  EB_APP_NAME         : "pet-clinic"
  EB_ENVIRONMENT_NAME : "petclinic-env"
  DEPLOYMENT_PACK_NAME: "pet_cl_${{ github.sha }}.zip"
  AWS_REGION          : "eu-west-1"

on: 
  push:
    branches: 
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Clone our repo 
      uses: actions/checkout@v1
    
    - name: Zip package
      run : zip -r ${{ env.DEPLOYMENT_PACK_NAME }} ./ -x *.git*
  
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION }} 

    - name: Copy package to S3
      run : |
             aws s3 cp ${{ env.DEPLOYMENT_PACK_NAME }} s3://${{ env.AWS_S3_BUCKET_NAME }}/
             echo "CI part finished successfully!"
      
